### ISSUE TITLE
Logs spammed with JAEGER ERROR operation=/,context=xxx  #You can only call finish() on a span once.

### ISSUE THREAD

**Issue by benoj** [chankamlam/express-jaeger#3]
Hi there,

not sure if this is maintained currently  - however I am getting lots of issues with calling finish on span once.

I have a simple middleware setup like so:

```
export const tracing = () =>
  jaeger(config, options, (req: any, res: any) => {
    res.set("X-Trace-Id", req.jaeger.span.context().traceIdStr)
  })
```

and in a simple instrumented post request I have the following:

```
  if (context?.jaeger) {
    const jaegerClient = context?.jaeger
    span = jaegerClient.createSpan(
      `remote_service_${target.serviceName}`,
      jaegerClient.span,
    )
    const spanContext = span.context()
    headers[
      "uber-trace-id"
    ] = `${spanContext.traceIdStr}:${spanContext.spanIdStr}:${spanContext.parentIdStr}:${spanContext.flags}`
  }
```

nowhere else do I use the tracing - any ideas what could be causing this issue?

**Comment by bender316** [comment]
It's not only that the log gets spammed but also you will be missing a lot of traces especially if your application is under load. Also the duration of a distributed span is not correctly propagated to jaeger.

It seems like express-jaeger has a serious design flaw so that one span gets shared across multiple requests. I have it patched here and now it does the desired thing.

If @chankamlam is still maintaining expres-jaeger I could provide a patch. Otherwise I could fork it but that would take time.

**Comment by chankamlam** [comment]
thx, guys for raise the issue ,let me take a look.

**Comment by chankamlam** [comment]
> It's not only that the log gets spammed but also you will be missing a lot of traces especially if your application is under load. Also the duration of a distributed span is not correctly propagated to jaeger.
> 
> It seems like express-jaeger has a serious design flaw so that one span gets shared across multiple requests. I have it patched here and now it does the desired thing.
> 
> If @chankamlam is still maintaining expres-jaeger I could provide a patch. Otherwise I could fork it but that would take time.

hi, buddy. maybe u can pull a request if u have patch for the issue. lets merge and fix it!

**Comment by bender316** [comment]
I just did a hotfix so that it works. I will look into it if there is a better solution and then will provide a pull request.
